spring:
  profiles:
    active: dev
  application:
    name: jt-order
  sleuth:
    integration:
      enabled: false
    sampler:
      percentage: 1
    scheduled:
      skip-pattern: ^org.*HystrixStreamTask$
  #  mvc:
  #    static-path-pattern: /static/**
  #    view:
  #      prefix: /WEB-INF/view

  http:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB



